//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<byte> COUNTRYID { get; set; }
        public Nullable<short> CITYID { get; set; }
        public Nullable<int> TOWNID { get; set; }
        public Nullable<int> DISTRICTID { get; set; }
        public string POSTALCODE { get; set; }
        public string ADDRESSTEXT { get; set; }
    }
}
