//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICTS
    {
        public int ID { get; set; }
        public Nullable<int> TOWNID { get; set; }
        public string DISTRICT { get; set; }
    
        public virtual TOWNS TOWNS { get; set; }
    }
}
