//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICEDETAILS
    {
        public int ID { get; set; }
        public Nullable<int> INVOICEID { get; set; }
        public Nullable<int> ORDERDETAILID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> LINETOTAL { get; set; }
    
        public virtual INVOICES INVOICES { get; set; }
        public virtual ORDERDETAILS ORDERDETAILS { get; set; }
    }
}
