//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERDETAILS()
        {
            this.INVOICEDETAILS = new HashSet<INVOICEDETAILS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> LINETOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICEDETAILS> INVOICEDETAILS { get; set; }
        public virtual ITEMS ITEMS { get; set; }
        public virtual ORDERS ORDERS { get; set; }
    }
}
