//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENTS
    {
        public int ID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<byte> PAYMENTTYPE { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<bool> ISOK { get; set; }
        public string APPROVECODE { get; set; }
        public Nullable<decimal> PAYMENTTOTAL { get; set; }
    }
}
