//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID { get; set; }
        public string USERNAME_ { get; set; }
        public string PASSWORD_ { get; set; }
        public string NAMESURNAME { get; set; }
        public string EMAIL { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string TELNR1 { get; set; }
        public string TELNR2 { get; set; }
    }
}
